import json
from jsonbender import bend, K, S

# Convert this Cloudrail's results format:
cloudrail_result = '[{"created_at": "2020-11-18 18:36:44Z", "rule_logic": "Cloudrail will iterate over all EC2 resources that use IAM roles. It will classify them between \"public\" (those that are accessible from the Internet) and \"private\" (those that are not). If an IAM role is determined to be associated with at least one public instance and at least one private instance, it will be considered in violation.", "status": "failed", "job_id": null, "rule_description": "Having the same IAM role for both public and private instances may be dangerous. Someone may expand the permissions for the role in order to use it in a private workload, not realizing a public workload has the same privileges.", "rule_name": "EC2(s) within the public and private subnets should not share identical IAM roles", "issue_items": [{"violating_entity": {"created_at": "2020-11-18T18:36:44.445942", "cloud_id": "aws_iam_role.test_role.id", "name": null, "id": "cebcf759-a03d-4419-9016-97f9a01551be", "cloud_arn": null, "tf_resource_metadata": {"start_line": 51, "address": "aws_iam_role.test_role", "id": "20f250fb-5c02-4231-93c9-4b9b8c784ec5", "block_text": "resource \"aws_iam_role\" \"test_role\" {\n  name = \"test_role\"\n\n  assume_role_policy = <<EOF\n{\n  \"Version\": \"2012-10-17\",\n  \"Statement\": [\n    {\n      \"Action\": \"sts:AssumeRole\",\n      \"Principal\": {\n        \"Service\": \"ec2.amazonaws.com\"\n      },\n      \"Effect\": \"Allow\",\n      \"Sid\": \"\"\n    }\n  ]\n}\nEOF\n\n}\n", "module_metadata": null, "file_name": "main.tf", "end_line": 70}, "tf_address": "aws_iam_role.test_role", "managed_by_tf": true, "is_pseudo": false, "type": "Role"}, "evidence": "~Instance ```['aws_instance.pub_ins']```~. Instance is publically exposed. Instance uses IAM role ```aws_iam_role.test_role```. Private EC2 instance shares IAM role ```aws_iam_role.test_role``` as well. ~Instance ```aws_instance.priv_ins.id```~", "exposed_entity": {"created_at": "2020-11-18T18:36:44.445942", "cloud_id": "aws_instance.priv_ins.id", "name": "aws_instance.priv_ins.id", "id": "22bcc4ee-9835-4210-a4aa-efc1973e7f1e", "cloud_arn": null, "tf_resource_metadata": {"start_line": 107, "address": "aws_instance.priv_ins", "id": "f4995ede-a101-4e25-8fab-eddee17681c6", "block_text": "resource \"aws_instance\" \"priv_ins\" {\n  ami           = \"${data.aws_ami.ubuntu.id}\"\n  instance_type = \"t2.micro\"\n  subnet_id = module.vpc.private_subnets[0]\n  iam_instance_profile = aws_iam_instance_profile.test_profile.name\n}", "module_metadata": null, "file_name": "main.tf", "end_line": 112}, "tf_address": "aws_instance.priv_ins", "managed_by_tf": true, "is_pseudo": false, "type": "Ec2 Instance"}}], "id": "eb637bf0-2619-4414-9869-5e79d3c3d587", "rule_id": "ec2_role_share_rule", "policy_name": null, "policy_id": null, "enforcement_mode": "advise"}]'

# Into this:
# https://docs.gitlab.com/12.10/ee/user/application_security/sast/#reports-json-format


